// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kkewzxmylbuzpspbiaid.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtrZXd6eG15bGJ1enBzcGJpYWlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5ODY3MTgsImV4cCI6MjA3MzU2MjcxOH0.Uxlcl-cLpMKbKp3lr9QKt1prSJfwn8F_nnUOYqLXd6g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});